### ISSUE TITLE
'cannot load such file' error when installed with bundler in rbenv

### ISSUE THREAD

**Issue by hoylemd** [tomdalling/byebug-skipper#1]
Hello there!

I stumbled upon this gem while looking for a solution to, well, the exact problem this seems intended to solve!  I work on a rails project, so whenever I'm debugging something, It's always a pain to step over 500,000 activerecord frames when trying to trace something, so being able to just jump over them based on their source file path would save me a ton of time and annoyance.

Unfortunately, I can't actually use this, as ruby seems to have trouble `requiring` it. I installed it with bundler, adding `gem 'byebug-skipper'` to my Gemfile, and running `bundle install` as normal.  I also use rbenv for version management since, which I suspect is part of the issue. When ruby tries to require it, I get the following error (`RBENV_PATH` is just `.rbenv` directory in my homedir)

```
$ ruby scratch.rb
<internal:RBENV_PATH/versions/3.2.2/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in `require': cannot load such file -- byebug-skipper (LoadError)
        from <internal:RBENV_PATH/versions/3.2.2/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from scratch.rb:3:in `<main>'
```

And the script I'm running to demonstrate the issue:

```
# scratch.rb
require 'byebug'
require 'byebug-skipper'

puts "hello"
byebug
puts "world"
```

I get similar results with ruby 2.6.6 (2.6.6 and 3.2.2 are the only versions I have set up locally).  My gut tells me rbenv is somehow getting in the way, but I don't know enough about how that or ruby's requiring works to understand why.

Any assistance in figuring out how to get this working would be appreciated!  Or if you're not maintaining this anymore, that's fine too.  Have a great day! 😃

**Comment by tomdalling** [comment]
Hi Michael,

Is that output copy-pasted exactly, or did you modify the parts that say `RBENV_PATH`? If it's actually outputting `RBENV_PATH` then that would probably indicate that something is wrong with it. It's likely caused by using `RBENV_PATH` instead of `$RBENV_PATH` in your shell config somewhere.

The other thing it could be is when you run `ruby scratch.rb` it can't access gems installed via Bundler. You could try `bundle exec ruby scratch.rb` in the same directory as the `Gemfile`, or you could try install the gem _without_ Bundler using just `gem install byebug-skipper` to make the gem available globally.

**Comment by tomdalling** [comment]
Nice investigating!

Yeah, whoops, it's definitely supposed to be `require 'byebug/skipper'`. I've updated `README.md` for that.

When I originally wrote the code, it would have been against `byebug` 11.1.3 and it was pretty difficult to get it working at all (see `HackyProcessor` in the source code). So I'm not surprised that it doesn't work with older versions. I should really set a minimum `byebug` version in the gemspec.

**Comment by hoylemd** [comment]
fixed in https://github.com/tomdalling/byebug-skipper/commit/a958c7a72aa0c91149623d11d5b42b3307536f42, https://github.com/tomdalling/byebug-skipper/pull/2 , and  https://github.com/tomdalling/byebug-skipper/commit/d1558b1e7db424e80680f20fd51313b52f76b37f
